#!/usr/bin/env bash

cmdline="$@"
start_date=$(date)
start_time=$(date '+%Y%m%d%H%M%S')
start_ts=$(date '+%s')
rundir="run/$start_time"

mkdir -p "$rundir"
cat >> "$rundir/_run_" <<EOF
Cmd: $cmdline
Start: $start_date
EOF

git add .
git commit --allow-empty -m "start: $rundir" -m "cmd: $cmdline"
commit=$(git rev-parse HEAD)
echo "Commit: $commit" >> "$rundir/_run_"

export RUNDIR="$rundir"
"$@" |& tee "$rundir/_out_"

exit_code=$?
stop_ts=$(date '+%s')
stop_date=$(date)
exec_time=$(($stop_ts - $start_ts))

cat >> "$rundir/_run_" <<EOF
Finish: $stop_date
Execution: $exec_time
Exit code: $exit_code
EOF

git add .
git commit --allow-empty -m "finish: $rundir" -m "cmd: $cmdline"

